### ISSUE TITLE
Error when running citygml-tiler

### ISSUE THREAD

**Issue by jailln** [VCityTeam/py3dtilers#139]
When running the citygml-tiler (installed from the master branch), I get the following error:

```
(venv) someone@someone:~/py3dtilers$ citygml-tiler --db_config_path ./py3dtilers/CityTiler/lyonTestConfig.yml --crs_in EPSG:3946 --crs_out EPSG:4978 --output_dir lyon_test-without-textures
Traceback (most recent call last):
  File "/home/admindc/py3dtilers/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/admindc/py3dtilers/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/admindc/py3dtilers/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.20.3 (/home/admindc/py3dtilers/venv/lib/python3.9/site-packages), Requirement.parse('numpy<1.25,>=1.21'), {'numba'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admindc/py3dtilers/venv/bin/citygml-tiler", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/admindc/py3dtilers/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/admindc/py3dtilers/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/admindc/py3dtilers/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/admindc/py3dtilers/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/admindc/py3dtilers/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/admindc/py3dtilers/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.20.3 (/home/admindc/py3dtilers/venv/lib/python3.9/site-packages), Requirement.parse('numpy<1.25,>=1.21'), {'numba'})

```

Do you have any idea why? Related to #137 ?

**Comment by LorenzoMarnat** [comment]
I've never had this error with py3dtilers

Can you give us the result of `pip list` when you are in the virtualenv ?

**Comment by jailln** [comment]
```
Package         Version      Location                
--------------- ------------ ------------------------
alphashape      1.3.1        
attrs           23.1.0       
certifi         2022.12.7    
click           8.1.3        
click-log       0.4.0        
Cython          0.29.34      
earclip         1.1          
ifcopenshell    0.7.0.230418 
jsonschema      4.17.3       
laspy           2.4.1        
libLAS          1.8.1        
llvmlite        0.40.0       
lz4             4.3.2        
networkx        3.1          
numba           0.57.0       
numpy           1.20.3       
Pillow          9.5.0        
pip             20.0.2       
pkg-resources   0.0.0        
psutil          5.9.5        
psycopg2        2.9.6        
psycopg2-binary 2.9.6        
py3dtilers      1.1.0        /home/admindc/py3dtilers
py3dtiles       1.1.0        
pyproj          3.5.0        
pyrsistent      0.19.3       
PyWavefront     1.3.3        
PyYAML          6.0          
pyzmq           25.0.2       
rdp             0.8          
Rtree           1.0.1        
scipy           1.10.1       
setuptools      44.0.0       
shapely         2.0.1        
triangle        20220202     
trimesh         3.21.5       
wheel           0.34.2  
```

**Comment by LorenzoMarnat** [comment]
I think I found the problem:

Py3DTilers needs numpy >=1.17,<1.21 in its [dependencies](https://github.com/VCityTeam/py3dtilers/blob/master/setup.py#L12)

Py3DTilers depends on Py3DTiles, which has [numba in its dependencies](https://github.com/VCityTeam/py3dtiles/blob/Tiler/setup.py#L16). It seems that the lastest version of numba (0.57.0) requires numpy >=1.21,<1.25:

```bash
(venv) PS D:\py3dtiles> pipdeptree
pip==22.0.4
pipdeptree==2.7.0
py3dtiles==2.0.0
  - cython [required: Any, installed: 0.29.34]
  - laspy [required: >=2.0,<3.0, installed: 2.4.1]
    - numpy [required: Any, installed: 1.22.4]
  - lz4 [required: Any, installed: 4.3.2]
  - numba [required: Any, installed: 0.57.0]
    - llvmlite [required: >=0.40.0dev0,<0.41, installed: 0.40.0]
    - numpy [required: >=1.21,<1.25, installed: 1.22.4]
  - numpy [required: >=1.20.0,<1.23, installed: 1.22.4]
  - psutil [required: Any, installed: 5.9.5]
  - psycopg2-binary [required: Any, installed: 2.9.6]
  - pyproj [required: Any, installed: 3.5.0]
    - certifi [required: Any, installed: 2022.12.7]
  - pyzmq [required: Any, installed: 25.0.2]
  - triangle [required: Any, installed: 20220202]
    - numpy [required: Any, installed: 1.22.4]
setuptools==58.1.0
```

I'll change Py3DTiles dependencies to force using numba 0.56.4, which is compatible with our numpy version:

```bash
    - numba [required: Any, installed: 0.56.4]
      - llvmlite [required: >=0.39.0dev0,<0.40, installed: 0.39.1]
      - numpy [required: >=1.18,<1.24, installed: 1.20.3]
      - setuptools [required: Any, installed: 58.1.0]
```

**Comment by LorenzoMarnat** [comment]
I've changed [Py3DTiles numba version](https://github.com/VCityTeam/py3dtiles/commit/c8199d8ca4d15d5ca7ad866aaef20f74e7138608)

Try running 

```bash
pip uninstall py3dtiles
pip install -e .
```

and let me know if the error still occurs

**Comment by jailln** [comment]
it worked thanks :)
