### ISSUE TITLE
Error when running the citygmltiler

### ISSUE THREAD

**Issue by jailln** [VCityTeam/py3dtilers#40]
I get the following error when running the CityGMLTiler:

```
Traceback (most recent call last):
  File "/home/vincent/Documents/dev/py3dtilers/venv/bin/citygml-tiler", line 33, in <module>
    sys.exit(load_entry_point('py3dtilers', 'console_scripts', 'citygml-tiler')())
  File "/home/vincent/Documents/dev/py3dtilers/py3dtilers/CityTiler/CityTiler.py", line 181, in main
    tileset = city_tiler.from_3dcitydb(cursor, objects_type, split_surfaces)
  File "/home/vincent/Documents/dev/py3dtilers/py3dtilers/CityTiler/CityTiler.py", line 129, in from_3dcitydb
    cityobjects = CityMCityObjects.retrieve_objects(cursor, objects_type)
  File "/home/vincent/Documents/dev/py3dtilers/py3dtilers/CityTiler/citym_cityobject.py", line 97, in retrieve_objects
    result_objects = objects_type()
  File "/home/vincent/Documents/dev/py3dtilers/py3dtilers/CityTiler/citym_building.py", line 45, in __init__
    super().__init__(objects)
  File "/home/vincent/Documents/dev/py3dtilers/py3dtilers/CityTiler/citym_cityobject.py", line 55, in __init__
    super().__init__(cityMCityObjects)
  File "/home/vincent/Documents/dev/py3dtilers/py3dtilers/Common/object_to_tile.py", line 99, in __init__
    ObjectsToTile.default_mat = ColorConfig().get_default_color()
  File "/home/vincent/Documents/dev/py3dtilers/py3dtilers/Color/color_config.py", line 19, in __init__
    with open(config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: './py3dtilers/Color/default_config.json'
```

Wrong filepath in last PR or missing default config ?

**Comment by LorenzoMarnat** [comment]
Are you running the Tiler from the root of the repo ? Since the path is relative, maybe the tiler can't find the config file.

**Comment by jailln** [comment]
I was running it from the `CityTiler` folder. Running it from the root of the repo works but I think it's a pity to constraint the tiler to run only from the root of the repository. Would it be possible to make this path relative to the file that needs it for instance ? Or to force the user to provide this file ? Or at least to put it in the documentation ?

**Comment by LorenzoMarnat** [comment]
The path to the default config file is now relative to the file. I'll add the possibility to provide the path to a config file later.

**Comment by jailln** [comment]
Thanks! :)
